export const PROVINCE_COLORS: Record<string, string> = {
  xinjiang: "#d8eadb",
  tibet: "#d7e5f0",
  qinghai: "#dce8ca",
  gansu: "#efe0bd",
  ningxia: "#e9d9bd",
  "inner-mongolia": "#dce8ca",
  heilongjiang: "#d2e3ef",
  jilin: "#d8eadb",
  liaoning: "#e6d8ec",
  beijing: "#f0c7b9",
  tianjin: "#f4d7b2",
  hebei: "#e9d9bd",
  shanxi: "#efe0bd",
  shaanxi: "#dce8ca",
  henan: "#f1d4c3",
  shandong: "#d7e5f0",
  jiangsu: "#cfe8df",
  anhui: "#e5e0c8",
  hubei: "#d8eadb",
  sichuan: "#d7e5f0",
  chongqing: "#e6d8ec",
  hunan: "#e5e0c8",
  jiangxi: "#d8eadb",
  zhejiang: "#cfe8df",
  shanghai: "#f0c7b9",
  fujian: "#d7e5f0",
  guizhou: "#e6d8ec",
  yunnan: "#d8eadb",
  guangxi: "#dce8ca",
  guangdong: "#f0c7b9",
  hainan: "#f4d7b2",
  "hong-kong": "#f0c7b9",
  macau: "#f4d7b2",
  taiwan: "#d7e5f0"
};

export const DEFAULT_PROVINCE_FILL = "#e1e8df";
